libpthread-sysdep_routines += init-arch
libpthread-sysdep_routines += elision-lock elision-unlock elision-timed \
			      elision-trylock \
			      pthread_mutex_lock-nortm \
			      pthread_mutex_trylock-nortm \
			      pthread_mutex_timedlock-nortm \
