libpthread-sysdep_routines += pthread_rwlock_rdlock-nortm pthread_rwlock_rdlock-rtm
libpthread-sysdep_routines += pthread_rwlock_wrlock-nortm pthread_rwlock_wrlock-rtm
libpthread-sysdep_routines += pthread_rwlock_timedrdlock-nortm pthread_rwlock_timedrdlock-rtm
libpthread-sysdep_routines += pthread_rwlock_timedwrlock-nortm pthread_rwlock_timedwrlock-rtm
