libpthread-sysdep_routines += adaptive-lock adaptive-unlock adaptive-timed
libpthread-sysdep_routines += pthread_arch_init adaptive-trylock
libpthread-sysdep_routines += pthread_rwlock_tryrdlock pthread_rwlock_trywrlock
