libpthread-sysdep_routines += elision-lock elision-unlock elision-timed
libpthread-sysdep_routines += elision-trylock
libpthread-sysdep_routines += pthread_rwlock_tryrdlock pthread_rwlock_trywrlock
libpthread-sysdep_routines += elision-mutex-lock elision-mutex-trylock
libpthread-sysdep_routines += pthread_mutex_lock pthread_mutex_trylock
